routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Site\HomeController@index');

Route::prefix('painel')->group(function () {
    Route::get('/', 'Admin\HomeController@index')->name('admin');

    Route::get('login', 'Admin\Auth\LoginController@index')->name('login');
    Route::post('login', 'Admin\Auth\LoginController@authenticate');

    Route::get('register', 'Admin\Auth\RegisterController@index')->name('register');
    Route::post('register', 'Admin\Auth\RegisterController@register');

    Route::get('password/email', 'Admin\Auth\ForgotPasswordController@index')->name('password.email');
    Route::post('password/email', 'Admin\Auth\ForgotPasswordController@forgotPassword');

    Route::post('logout', 'Admin\Auth\LoginController@logout')->name('logout');

    Route::resource('users', 'Admin\UserController');
    Route::resource('pages', 'Admin\PageController');
    Route::resource('categories', 'Admin\CategorieController');

    Route::get('profile','Admin\ProfileController@index')->name('profile');
    Route::put('profile', 'Admin\ProfileController@save')->name('profile.save');

    Route::get('settings', 'Admin\SettingController@index')->name('settings');
    Route::put('settingsave', 'Admin\SettingController@save')->name('settings.save');

    Route::get('homesearch', 'Admin\HomeController@index')->name('home.index');

    Route::get('publications', 'Admin\PublicationController@index')->name('publications.index');

    Route::get('categoriesedit', 'Admin\CategorieController@edit')->name('categories.edit');
    Route::post('categoriesdestroy', 'Admin\CategorieController@destroy')->name('categories.destroy');
    Route::post('categoriesdestore', 'Admin\CategorieController@store')->name('categories.store');
});

Route::fallback('Site\PageController@index');

resources/views/admin/pages/create.blade.php
@extends('adminlte::page')

@section('title', 'Nova Página')

@section('content')
    <div class="container">
        <div class="card card-outline card-info">
            <div class="card-header">
                <h3 class="card-title">Nova Página</h3>
            </div>
            <!-- /.box-header -->

            @if ($errors->any())
                <div class="callout alert-danger callout-danger">
                    <h4><i class="icon fa fa-ban"></i> Erro!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <!-- form start -->
            <form method="POST" action="{{ route('pages.store') }}" class="form-horizontal">
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="title" class="col-sm-2 control-label">Títutlo</label>
                        <div class="col-sm">
                            <input type="text" id="title" name="title" value="{{ old('title') }}" placeholder="Titulo"
                                class="form-control @error('title') is-invalid @enderror">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="body" class="col-sm-2 control-label">Corpo</label>
                        <div class="col-sm">
                            <textarea name="body" class="form-control bodytextarea">{{ old('body') }}</textarea>
                        </div>
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    <button type="submit" class="btn btn-info">Criar</button>
                </div>
                <!-- /.card-footer -->
            </form>
        </div>
    </div>

    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin')"></script>
    <script>
        tinymce.init({
            selector: 'textarea.bodytextarea',
            height: 300,
            menubar: false,
            plugins: ['link', 'table', 'lists', 'autoresize', 'image'],
            toolbar: 'fontselect | fontsizeselect | undo redo | formatselect | bold italic backcolor | alignleft aligncenter alignright alignjustify | rotateleft rotateright | imageoptions | table | link image | bullist numlist',
            content_css: ['{{ asset('assets/css/content.css') }}'],
            fontsize_formats: '8pt 10pt 12pt 14pt 16pt 18pt 24pt 36pt 48pt',
            font_formats: 'Andale Mono=andale mono,times; Arial=arial,helvetica,sans-serif; Arial Black=arial black,avant garde; Book Antiqua=book antiqua,palatino; Comic Sans MS=comic sans ms,sans-serif; Courier New=courier new,courier; Georgia=georgia,palatino; Helvetica=helvetica; Impact=impact,chicago; Symbol=symbol; Tahoma=tahoma,arial,helvetica,sans-serif; Terminal=terminal,monaco; Times New Roman=times new roman,times; Trebuchet MS=trebuchet ms,geneva; Verdana=verdana,geneva; Webdings=webdings; Wingdings=wingdings,zapf dingbats',
            //images_upload_url: '{{ route('imageupload') }}',
            images_upload_credentials: true,
            convert_urls: false
        });

    </script>
@endsection

resources/views/admin/pages/edit.blade.php
@extends('adminlte::page')

@section('title', 'Editar Página')

@section('content')

    <div class="container">
        <div class="card card-outline card-info">
            <div class="card-header">
                <h3 class="card-title">Editar Página</h3>
            </div>
            <!-- /.card-header -->

            @if ($errors->any())
                <div class="callout alert-danger callout-danger">
                    <h4><i class="icon fa fa-ban"></i> Erro!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <!-- form start -->
            <form method="POST" action="{{ route('pages.update', ['page' => $page->id]) }}" class="form-horizontal">
                @method('PUT')
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="title" class="col-sm-2 control-label">Titulo</label>
                        <div class="col-sm">
                            <input type="text" class="form-control @error('title') is-invalid @enderror" id="title"
                                name="title" value="{{ $page->title }}" placeholder="Titulo">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="body" class="col-sm-2 control-label">Corpo</label>
                        <div class="col-sm">
                            <textarea name="body" class="form-control bodytextarea">{{ $page->body }}</textarea>
                        </div>
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    <button type="submit" class="btn btn-success">Alterar</button>
                </div>
                <!-- /.card-footer -->
            </form>
        </div>
    </div>

    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin'"></script>
    <script>
        tinymce.init({
            selector: 'textarea.bodytextarea',
            height: 300,
            menubar: false,
            plugins: ['link', 'table', 'lists', 'autoresize', 'image'],
            toolbar: 'fontselect | fontsizeselect | undo redo | formatselect | bold italic backcolor | alignleft aligncenter alignright alignjustify | rotateleft rotateright | imageoptions | table | link image | bullist numlist',
            content_css: ['{{asset('assets/css/content.css')}}'],
            fontsize_formats: '8pt 10pt 12pt 14pt 16pt 18pt 24pt 36pt 48pt',
            font_formats: 'Andale Mono=andale mono,times; Arial=arial,helvetica,sans-serif; Arial Black=arial black,avant garde; Book Antiqua=book antiqua,palatino; Comic Sans MS=comic sans ms,sans-serif; Courier New=courier new,courier; Georgia=georgia,palatino; Helvetica=helvetica; Impact=impact,chicago; Symbol=symbol; Tahoma=tahoma,arial,helvetica,sans-serif; Terminal=terminal,monaco; Times New Roman=times new roman,times; Trebuchet MS=trebuchet ms,geneva; Verdana=verdana,geneva; Webdings=webdings; Wingdings=wingdings,zapf dingbats',
            //images_upload_url: '{{route('imageupload')}}',
            images_upload_credentials:true,
            convert_urls:false
        });

    </script>

@endsection

resources/views/admin/pages/index.blade.php
@extends('adminlte::page')

@section('title', 'Usuários')
@section('content_header')
    <h1>
        Minhas Páginas
        <a href="{{ route('pages.create') }}" class="btn btn-sm btn-success">Nova Página</a>
    </h1>
@endsection
@section('content')
    <div class="container">
        <div class="card">
            <div class="card-body">
                <table class="table table-hover table-rounded">
                    <thead>
                        <tr>
                            <th width="50">#</th>
                            <th s>Título</th>
                            <th width="200">Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($pages as $page)
                            <tr>
                                <td scope="row">{{ $page->id }}</td>
                                <td>{{ $page->title }}</td>
                                <td>
                                    <a href="#" target="_blank" class="btn btn-sm btn-success">Ver</a>
                                    <a href="{{ route('pages.edit', ['page' => $page->id]) }}"
                                        class="btn btn-sm btn-warning">Editar</a>

                                    <form class="d-inline" action="{{ route('pages.destroy', ['page' => $page->id]) }}"
                                        method="post" onsubmit="return confirm('Tem certeza que deseja excluir?')">
                                        @method('DELETE')
                                        @csrf
                                        <button class="btn btn-sm btn-danger">Excluir</button>
                                    </form>

                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        {{ $pages->links() }}
    </div>
@endsection